name: Simple Deploy to Cloud Run and Vercel

on:
  push:
    branches: [ main ]

env:
  PROJECT_ID: hackathon-462905
  REGION: asia-northeast1

jobs:
  deploy-backend:
    name: Deploy Backend to Cloud Run
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Authenticate to Google Cloud
      uses: google-github-actions/auth@v2
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}
    
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v2
    
    - name: Deploy to Cloud Run
      run: |
        cd backend
        gcloud run deploy infumatch-backend \
          --source=. \
          --platform=managed \
          --region=${{ env.REGION }} \
          --allow-unauthenticated \
          --port=8000 \
          --memory=1Gi \
          --cpu=1 \
          --timeout=300 \
          --min-instances=0 \
          --max-instances=3 \
          --execution-environment=gen2 \
          --set-env-vars="GOOGLE_CLOUD_PROJECT_ID=${{ env.PROJECT_ID }},GOOGLE_CLOUD_REGION=${{ env.REGION }}" \
          --project=${{ env.PROJECT_ID }}

  deploy-frontend:
    name: Deploy Frontend to Vercel
    runs-on: ubuntu-latest
    needs: deploy-backend
    
    steps:
    - name: Checkout
      uses: actions/checkout@v4
    
    - name: Deploy to Vercel
      uses: amondnet/vercel-action@v25
      with:
        vercel-token: ${{ secrets.VERCEL_TOKEN }}
        vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
        vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID }}
        working-directory: ./frontend
        vercel-args: '--prod'